import { useEffect, useState, type FormEvent } from "react";
import { Edit, Plus, Trash2 } from "lucide-react";
import { Badge, Button, Card, CurrencyInput, Field, Money, PageHeader, ProgressBar, Skeleton, inputClass } from "../components/ui";
import { ConfirmDialog, Modal, useFeedback } from "../components/feedback";
import { percent } from "../lib/format";
import { api, type Budget, type Category } from "../lib/api";

function budgetTone(used: number) { if (used >= 100) return { bar: "bg-red-500", badge: "Ultrapassado", variant: "negative" as const }; if (used >= 75) return { bar: "bg-amber-500", badge: "Atenção", variant: "warning" as const }; return { bar: "bg-emerald-500", badge: "Saudável", variant: "positive" as const }; }

export default function BudgetPage() {
  const [items, setItems] = useState<Budget[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [summary, setSummary] = useState({ limit: 0, spent: 0, remaining: 0 }); const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Budget | null>(null); const [limit, setLimit] = useState(0); const [deleting, setDeleting] = useState<Budget | null>(null); const { notify } = useFeedback();
  const now = new Date();
  async function load() { setLoading(true); try { const [budgets, categoryData] = await Promise.all([api<{ items: Budget[]; summary: typeof summary }>(`/budgets?month=${now.getMonth()+1}&year=${now.getFullYear()}`), api<{ items: Category[] }>("/categories")]); setItems(budgets.items); setSummary(budgets.summary); setCategories(categoryData.items.filter((item) => item.type !== "income")); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao carregar orçamentos.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (limit <= 0) return notify("Informe um limite maior que zero.", "error"); try { if (editing) await api(`/budgets/${editing.id}`, { method: "PUT", body: JSON.stringify({ limit, is_recurring: data.get("recurring") === "on" }) }); else await api("/budgets", { method: "POST", body: JSON.stringify({ category_id: data.get("category_id"), month: now.getMonth()+1, year: now.getFullYear(), limit, is_recurring: data.get("recurring") === "on" }) }); setOpen(false); setEditing(null); await load(); notify("Orçamento salvo."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao salvar.", "error"); } }
  async function remove() { if (!deleting) return; try { await api(`/budgets/${deleting.id}`, { method: "DELETE" }); setDeleting(null); await load(); notify("Orçamento excluído."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao excluir.", "error"); } }
  const used = summary.limit ? summary.spent / summary.limit * 100 : 0;
  return <>
    <PageHeader title="Orçamento" subtitle={`${now.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })} · ${percent(used)} utilizado`} actions={<Button icon={Plus} onClick={() => { setEditing(null); setLimit(0); setOpen(true); }}>Novo orçamento</Button>} />
    <Card><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-slate-500">Gasto total</p><p className="mt-1 text-2xl font-semibold"><Money value={summary.spent} color={false} /> <span className="text-sm font-normal text-slate-500">de {summary.limit.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</span></p></div><p className="text-sm text-slate-500">Restante: {summary.remaining.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</p></div><div className="mt-4"><ProgressBar value={used} color={budgetTone(used).bar} /></div></Card>
    {loading ? <Skeleton className="mt-6 h-72" /> : <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((budget) => { const pct = budget.limit ? budget.spent / budget.limit * 100 : 0; const tone = budgetTone(pct); return <Card key={budget.id} className="group surface-hover"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{budget.category}</h2><p className="money mt-2 text-lg font-semibold"><Money value={budget.spent} color={false} /> <span className="text-sm font-normal text-slate-500">/ {budget.limit.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</span></p></div><Badge variant={tone.variant}>{tone.badge}</Badge></div><div className="mt-4"><ProgressBar value={pct} color={tone.bar} /></div><div className="mt-3 flex justify-between text-sm text-slate-500"><span>{percent(pct)}</span><span>{Math.abs(budget.limit-budget.spent).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })} {budget.spent>budget.limit?"acima":"restantes"}</span></div><div className="mt-4 flex gap-2"><Button variant="outline" icon={Edit} onClick={() => { setEditing(budget); setLimit(budget.limit); setOpen(true); }}>Editar</Button><Button variant="ghost" icon={Trash2} onClick={() => setDeleting(budget)}>Excluir</Button></div></Card>; })}{!items.length && <p className="text-sm text-slate-500">Nenhum orçamento definido para este mês.</p>}</section>}
    <Modal open={open} title="Definir orçamento" onClose={() => setOpen(false)} footer={<><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" form="budget-form">Salvar orçamento</Button></>}><form id="budget-form" className="grid gap-4" onSubmit={save}><Field label="Categoria"><select name="category_id" className={inputClass} required disabled={Boolean(editing)} defaultValue={editing?.category_id ?? ""}><option value="">Selecione</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Valor limite"><CurrencyInput initialValue={editing?.limit} onValueChange={setLimit} required /></Field><label className="flex items-center justify-between rounded-lg border p-3 text-sm">Repetir todos os meses<input name="recurring" type="checkbox" className="h-4 w-4" defaultChecked={editing?.is_recurring} /></label></form></Modal>
    <ConfirmDialog open={Boolean(deleting)} title="Excluir orçamento?" description={`O orçamento de ${deleting?.category ?? "esta categoria"} será removido.`} onClose={() => setDeleting(null)} onConfirm={() => void remove()} />
  </>;
}
