import { useEffect, useState, type FormEvent } from "react";
import { Calendar, Plus, Target } from "lucide-react";
import { Badge, Button, Card, CurrencyInput, Field, Money, PageHeader, ProgressBar, Skeleton, inputClass } from "../components/ui";
import { Modal, useFeedback } from "../components/feedback";
import { api, type Account, type Goal } from "../lib/api";

export default function GoalsPage() {
  const [items, setItems] = useState<Goal[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [contributing, setContributing] = useState<Goal | null>(null); const [target, setTarget] = useState(0); const [saved, setSaved] = useState(0); const [contribution, setContribution] = useState(0); const { notify } = useFeedback();
  async function load() { setLoading(true); try { const [goals, accountData] = await Promise.all([api<{ items: Goal[] }>("/goals"), api<{ items: Account[] }>("/accounts")]); setItems(goals.items); setAccounts(accountData.items); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao carregar metas.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const totalTarget = items.reduce((sum, goal) => sum + goal.target, 0); const totalSaved = items.reduce((sum, goal) => sum + goal.saved, 0);
  async function saveGoal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (target <= 0) return notify("Informe um valor alvo.", "error"); try { await api("/goals", { method: "POST", body: JSON.stringify({ name: data.get("name"), target, saved, deadline: data.get("deadline"), account_id: data.get("account_id") || null, description: data.get("description"), monthly: 0 }) }); setOpen(false); await load(); notify("Meta criada com sucesso."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao criar meta.", "error"); } }
  async function addContribution() { if (!contributing || contribution <= 0) return; try { await api(`/goals/${contributing.id}/contributions`, { method: "POST", body: JSON.stringify({ amount: contribution, date: new Date().toISOString().slice(0,10) }) }); setContributing(null); setContribution(0); await load(); notify("Aporte registrado."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao registrar aporte.", "error"); } }
  return <>
    <PageHeader title="Metas Financeiras" subtitle={`${items.filter((item) => item.status !== "completed").length} metas ativas · ${items.filter((item) => item.status === "completed").length} concluídas`} actions={<Button icon={Plus} onClick={() => setOpen(true)}>Nova meta</Button>} />
    <section className="grid gap-4 md:grid-cols-3"><Summary label="Total almejado" value={totalTarget} /><Summary label="Total acumulado" value={totalSaved} detail={totalTarget ? `${((totalSaved/totalTarget)*100).toFixed(1)}% concluído` : "Sem metas"} /><Card><p className="text-sm text-slate-500">Metas ativas</p><div className="mt-3"><Badge variant="positive">{items.filter((item) => item.status === "active").length} em andamento</Badge></div></Card></section>
    {loading ? <Skeleton className="mt-6 h-72" /> : <section className="mt-6 grid gap-4 xl:grid-cols-2">{items.map((goal) => { const progress=Math.min(goal.saved/goal.target*100,100); const remaining=Math.max(goal.target-goal.saved,0); const done=goal.status==="completed"; return <Card key={goal.id} className={done?"opacity-75":"surface-hover"}><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-primary"><Target className="h-5 w-5" /></span><div><h2 className="text-lg font-semibold">{goal.name}</h2><Badge variant={done?"neutral":"positive"}>{done?"Concluída":"Em andamento"}</Badge></div></div><div className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><Money className="text-3xl font-semibold text-primary" value={goal.saved} color={false} /><span className="ml-2 text-sm text-slate-500">de {goal.target.toLocaleString("pt-BR", { style:"currency",currency:"BRL" })}</span></div><strong className="text-sm text-slate-700">{progress.toFixed(1)}%</strong></div><div className="mt-4"><ProgressBar value={progress} color={done?"bg-emerald-500":"bg-blue-500"} /></div><div className="mt-5 grid gap-3 rounded-lg bg-slate-50 p-4 text-sm text-slate-600 sm:grid-cols-2"><span><Calendar className="mr-1 inline h-4 w-4" />{new Date(`${goal.deadline}T12:00:00`).toLocaleDateString("pt-BR")}</span><span>Restante: <strong>{remaining.toLocaleString("pt-BR", { style:"currency",currency:"BRL" })}</strong></span></div>{!done && <Button className="mt-5 w-full" variant="outline" onClick={() => setContributing(goal)}>Registrar aporte</Button>}</Card>; })}{!items.length && <p className="text-sm text-slate-500">Nenhuma meta cadastrada.</p>}</section>}
    <Modal open={open} title="Nova meta financeira" subtitle="Defina o objetivo e acompanhe o progresso." onClose={() => setOpen(false)} footer={<><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" form="goal-form">Salvar meta</Button></>}><form id="goal-form" className="grid gap-4" onSubmit={saveGoal}><Field label="Nome da meta"><input name="name" className={inputClass} required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Valor alvo"><CurrencyInput onValueChange={setTarget} required /></Field><Field label="Valor atual"><CurrencyInput onValueChange={setSaved} /></Field></div><Field label="Prazo"><input name="deadline" type="date" className={inputClass} required /></Field><Field label="Conta vinculada"><select name="account_id" className={inputClass}><option value="">Sem conta vinculada</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Descrição"><textarea name="description" className="min-h-24 w-full rounded-lg border border-slate-300 p-3 text-sm" /></Field></form></Modal>
    <Modal open={Boolean(contributing)} title={`Aporte em ${contributing?.name ?? "meta"}`} onClose={() => setContributing(null)} footer={<><Button variant="outline" onClick={() => setContributing(null)}>Cancelar</Button><Button onClick={() => void addContribution()}>Registrar aporte</Button></>}><Field label="Valor do aporte"><CurrencyInput onValueChange={setContribution} required /></Field></Modal>
  </>;
}
function Summary({ label,value,detail }: { label:string;value:number;detail?:string }) { return <Card><p className="text-sm text-slate-500">{label}</p><Money className="mt-2 block text-2xl font-semibold" value={value} color={false} />{detail&&<p className="mt-2 text-xs text-slate-500">{detail}</p>}</Card>; }
