import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CreditCard, Plus, Trash2 } from "lucide-react";
import { Badge, Button, Card, CurrencyInput, EmptyState, Field, Money, PageHeader, Skeleton, inputClass } from "../components/ui";
import { ConfirmDialog, Modal, useFeedback } from "../components/feedback";
import { cn } from "../lib/format";
import { api, toDateLabel, type Account, type Bill, type Category } from "../lib/api";

const tabs = ["Todas", "A Pagar", "A Receber", "Vencidas", "Pagas"];
type BillSummary = { payable: number; receivable: number; overdue: number; forecast: number };

export default function PayablesPage() {
  const [items, setItems] = useState<Bill[]>([]); const [summary, setSummary] = useState<BillSummary>({ payable: 0, receivable: 0, overdue: 0, forecast: 0 });
  const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState("Todas"); const [modalOpen, setModalOpen] = useState(false); const [kind, setKind] = useState<"payable" | "receivable">("payable"); const [amount, setAmount] = useState(0); const [deleting, setDeleting] = useState<Bill | null>(null); const { notify } = useFeedback();
  async function load() { setLoading(true); try { const [bills, accountData, categoryData] = await Promise.all([api<{ items: Bill[]; summary: BillSummary }>("/bills"), api<{ items: Account[] }>("/accounts"), api<{ items: Category[] }>("/categories")]); setItems(bills.items); setSummary(bills.summary); setAccounts(accountData.items); setCategories(categoryData.items); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao carregar contas.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter((item) => tab === "Todas" || (tab === "A Pagar" && item.type === "payable") || (tab === "A Receber" && item.type === "receivable") || (tab === "Vencidas" && item.status === "overdue") || (tab === "Pagas" && item.status === "paid")), [items, tab]);
  function openForm(next: "payable" | "receivable") { setKind(next); setModalOpen(true); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (amount <= 0) return notify("Informe um valor maior que zero.", "error"); try { await api("/bills", { method: "POST", body: JSON.stringify({ type: kind, description: data.get("description"), amount, due_date: data.get("due_date"), category_id: data.get("category_id") || null, account_id: data.get("account_id") || null, is_recurring: data.get("recurring") === "on", notes: data.get("notes") }) }); setModalOpen(false); setAmount(0); await load(); notify("Conta criada com sucesso."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao salvar.", "error"); } }
  async function settle(item: Bill) { try { await api(`/bills/${item.id}/pay`, { method: "POST", body: JSON.stringify({ amount: item.amount - item.paid_amount, paid_at: new Date().toISOString().slice(0,10) }) }); await load(); notify(item.type === "receivable" ? "Recebimento confirmado." : "Pagamento confirmado."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao liquidar conta.", "error"); } }
  async function remove() { if (!deleting) return; try { await api(`/bills/${deleting.id}`, { method: "DELETE" }); setDeleting(null); await load(); notify("Conta excluída."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao excluir.", "error"); } }

  return <>
    <PageHeader title="Contas a Pagar e Receber" subtitle="Valores calculados a partir dos registros persistidos" actions={<><Button variant="outline" icon={Plus} className="text-red-600" onClick={() => openForm("payable")}>Nova conta a pagar</Button><Button variant="success" icon={Plus} onClick={() => openForm("receivable")}>Nova conta a receber</Button></>} />
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["A Pagar",summary.payable,"pendente"],["A Receber",summary.receivable,"pendente"],["Em atraso",summary.overdue,"vencido"],["Saldo Previsto",summary.forecast,"após vencimentos"]].map(([title,value,meta]) => <Card key={String(title)}><p className="text-sm text-slate-500">{title}</p><Money className="mt-2 block text-2xl font-semibold" value={Number(value)} /><p className="mt-2 text-xs text-slate-500">{meta}</p></Card>)}</section>
    <Card className="mt-6"><div className="flex gap-1 overflow-x-auto rounded-lg bg-slate-100 p-1">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("min-w-max rounded-md px-3 py-2 text-sm", tab === item ? "bg-white font-semibold text-primary shadow-sm" : "text-slate-600")}>{item}</button>)}</div></Card>
    {loading ? <Skeleton className="mt-4 h-72" /> : <section className="mt-4 space-y-3">{filtered.length === 0 && <EmptyState icon={CreditCard} title="Nenhuma conta encontrada" subtitle="Cadastre uma conta a pagar ou receber para começar." />}{filtered.map((item) => { const late = item.status === "overdue"; const paid = item.status === "paid"; const income = item.type === "receivable"; return <Card key={item.id} className={cn("border-l-4", late ? "border-l-red-500 bg-red-50/40" : paid ? "border-l-slate-300 opacity-75" : income ? "border-l-emerald-500" : "border-l-blue-500")}><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><CreditCard className="h-5 w-5 text-slate-500" /><h2 className="font-semibold">{item.description}</h2><Badge variant={late ? "negative" : paid ? "positive" : income ? "info" : "warning"}>{income ? "A RECEBER" : "A PAGAR"}</Badge><Badge variant={late ? "negative" : paid ? "positive" : "neutral"}>{item.status.toUpperCase()}</Badge></div><p className="mt-2 text-sm text-slate-500">{item.category} · {item.account || "Sem conta"} · vencimento {toDateLabel(item.due_date)}</p></div><div className="flex flex-col gap-3 lg:items-end"><Money className="text-xl font-semibold" value={item.amount - item.paid_amount} color={false} /><div className="flex flex-wrap gap-1">{!paid && item.account_id && <Button variant={income ? "success" : "primary"} onClick={() => void settle(item)}>{income ? "Marcar recebido" : "Marcar pago"}</Button>}<Button variant="ghost" icon={Trash2} onClick={() => setDeleting(item)} aria-label="Excluir" /></div></div></div></Card>; })}</section>}
    <Modal open={modalOpen} title={kind === "payable" ? "Nova conta a pagar" : "Nova conta a receber"} onClose={() => setModalOpen(false)} footer={<><Button variant="outline" onClick={() => setModalOpen(false)}>Cancelar</Button><Button type="submit" form="bill-form">Salvar conta</Button></>} size="lg"><form id="bill-form" onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><select className={inputClass} value={kind} onChange={(event) => setKind(event.target.value as "payable" | "receivable")}><option value="payable">A pagar</option><option value="receivable">A receber</option></select></Field><Field label="Descrição"><input name="description" className={inputClass} required /></Field><Field label="Valor"><CurrencyInput onValueChange={setAmount} required /></Field><Field label="Data de vencimento"><input name="due_date" type="date" className={inputClass} required /></Field><Field label="Categoria"><select name="category_id" className={inputClass}><option value="">Sem categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Conta associada"><select name="account_id" className={inputClass}><option value="">Selecione ao liquidar</option>{accounts.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><label className="flex h-11 items-center justify-between self-end rounded-lg border px-3 text-sm">Recorrente<input name="recurring" type="checkbox" /></label><div className="sm:col-span-2"><Field label="Observações"><textarea name="notes" className="min-h-24 w-full rounded-lg border border-slate-300 p-3 text-sm" /></Field></div></form></Modal>
    <ConfirmDialog open={Boolean(deleting)} title="Excluir conta?" description={`A conta “${deleting?.description ?? ""}” será removida.`} onClose={() => setDeleting(null)} onConfirm={() => void remove()} />
  </>;
}
