import { useMemo, useState, type FormEvent } from "react";
import { Copy, Edit, Plus, Search, Trash2, Upload, X } from "lucide-react";
import { transactions } from "../data/mock";
import { Badge, Button, Card, CurrencyInput, Field, Money, PageHeader, inputClass } from "../components/ui";
import { ConfirmDialog, Modal, useFeedback } from "../components/feedback";
import { cn } from "../lib/format";

type Transaction = typeof transactions[number];

export default function TransactionsPage() {
  const [items, setItems] = useState(transactions);
  const [query, setQuery] = useState(""); const [type, setType] = useState("Todas"); const [account, setAccount] = useState("Todas"); const [category, setCategory] = useState("Todas");
  const [minValue, setMinValue] = useState(""); const [maxValue, setMaxValue] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  const [drawerOpen, setDrawerOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [deleting, setDeleting] = useState<string | null>(null);
  const { notify } = useFeedback();
  const filtered = useMemo(() => items.filter((item) => { const value = Math.abs(item.value); return item.description.toLowerCase().includes(query.toLowerCase()) && (type === "Todas" || (type === "Receitas" && item.value > 0) || (type === "Despesas" && item.value < 0)) && (account === "Todas" || item.account === account) && (category === "Todas" || item.category === category) && (!minValue || value >= Number(minValue)) && (!maxValue || value <= Number(maxValue)); }), [items, query, type, account, category, minValue, maxValue]);

  return (
    <>
      <PageHeader title="Transações" subtitle={`${items.length} lançamentos · R$ 3.739,70 de resultado`} actions={<><Button variant="outline" icon={Upload} onClick={() => setImportOpen(true)}>Importar extrato</Button><Button icon={Plus} onClick={() => setDrawerOpen(true)}>Nova transação</Button></>} />
      <Card className="sticky top-16 z-10 mb-4 shadow-sm lg:top-0">
        <div className="grid gap-3 lg:grid-cols-[minmax(220px,1.4fr)_180px_280px_160px_160px]"><div className="relative"><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400" /><input className={cn(inputClass,"pl-10")} placeholder="Buscar transações..." value={query} onChange={(event) => setQuery(event.target.value)} /></div><input className={inputClass} value="01/06/2026 - 30/06/2026" readOnly /><div className="grid grid-cols-3 rounded-lg bg-slate-100 p-1">{["Todas","Receitas","Despesas"].map((item) => <button key={item} onClick={() => setType(item)} className={cn("rounded-md px-2 py-1.5 text-sm",type === item ? "bg-white font-semibold text-primary shadow-sm" : "text-slate-600")}>{item}</button>)}</div><select className={inputClass} value={account} onChange={(event) => setAccount(event.target.value)}><option value="Todas">Todas as contas</option><option>Nubank</option><option>Poupança</option><option>Cartão</option></select><select className={inputClass} value={category} onChange={(event) => setCategory(event.target.value)}><option value="Todas">Todas categorias</option>{[...new Set(items.map((item) => item.category))].map((item) => <option key={item}>{item}</option>)}</select></div>
        <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:max-w-md"><input className={inputClass} type="number" min="0" placeholder="Valor mínimo" value={minValue} onChange={(event) => setMinValue(event.target.value)} /><input className={inputClass} type="number" min="0" placeholder="Valor máximo" value={maxValue} onChange={(event) => setMaxValue(event.target.value)} /></div>
      </Card>
      <section className="mb-4 grid gap-4 md:grid-cols-3"><Summary label="Total de receitas" value={12500} /><Summary label="Total de despesas" value={-8760.3} /><Summary label="Resultado" value={3739.7} /></section>
      {selected.length > 0 && <div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border bg-blue-50 p-3 text-sm"><strong>{selected.length} selecionadas</strong><Button variant="outline">Categorizar</Button><Button variant="danger" onClick={() => setDeleting("selecionadas")}>Excluir</Button><Button variant="ghost" onClick={() => setSelected([])}>Cancelar</Button></div>}
      <Card className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="w-10 px-4 py-3"></th><th className="px-4 py-3">Descrição</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Conta</th><th className="px-4 py-3">Data</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3 text-right">Ações</th></tr></thead><tbody>{filtered.length === 0 && <tr><td colSpan={7} className="px-4 py-16 text-center"><strong className="block text-slate-800">Nenhuma transação encontrada</strong><span className="mt-1 block text-sm text-slate-500">Ajuste a busca, conta, categoria ou faixa de valor.</span></td></tr>}{filtered.map((item) => <tr key={`${item.description}-${item.date}`} className="border-t hover:bg-slate-50"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item.description)} onChange={(event) => setSelected((current) => event.target.checked ? [...current,item.description] : current.filter((value) => value !== item.description))} /></td><td className="px-4 py-3 font-medium">{item.description}</td><td className="px-4 py-3"><Badge>{item.category}</Badge></td><td className="px-4 py-3 text-slate-600">{item.account}</td><td className="px-4 py-3 text-slate-600">{item.date}</td><td className="px-4 py-3 text-right"><Money value={item.value} signed /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><IconButton label="Editar" icon={Edit} onClick={() => setDrawerOpen(true)} /><IconButton label="Duplicar" icon={Copy} onClick={() => { setItems((current) => [{...item,description:`${item.description} (cópia)`},...current]); notify("Transação duplicada."); }} /><IconButton label="Excluir" icon={Trash2} danger onClick={() => setDeleting(item.description)} /></div></td></tr>)}</tbody></table></div><div className="flex flex-col gap-3 border-t px-4 py-3 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>Mostrando {filtered.length} de {items.length} transações</span><div className="flex gap-2"><Button variant="outline">Anterior</Button><Button variant="outline">Próxima</Button></div></div></Card>
      {drawerOpen && <TransactionDrawer onClose={() => setDrawerOpen(false)} onSave={(item) => { setItems((current) => [item,...current]); setDrawerOpen(false); notify("Transação salva com sucesso."); }} />}
      <ImportDialog open={importOpen} onClose={() => setImportOpen(false)} onComplete={() => { setImportOpen(false); notify("18 transações importadas."); }} />
      <ConfirmDialog open={Boolean(deleting)} title="Excluir transação?" description={deleting === "selecionadas" ? `${selected.length} transações serão excluídas.` : `A transação “${deleting ?? ""}” será excluída.`} onClose={() => setDeleting(null)} onConfirm={() => { setItems((current) => deleting === "selecionadas" ? current.filter((item) => !selected.includes(item.description)) : current.filter((item) => item.description !== deleting)); setSelected([]); setDeleting(null); notify("Transação excluída."); }} />
    </>
  );
}

function TransactionDrawer({ onClose, onSave }: { onClose: () => void; onSave: (item: Transaction) => void }) {
  const [kind,setKind] = useState("Despesa"); const [value,setValue] = useState(0); const [recurring,setRecurring] = useState(false); const [installment,setInstallment] = useState(false); const { notify } = useFeedback();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const description = String(data.get("description")); const date = String(data.get("date")); if (!description || !date || value <= 0) return notify("Preencha descrição, valor e data.","error"); onSave({ description, category: kind === "Transferência" ? "Transferência" : String(data.get("category")), account: String(data.get("account")), date: new Date(date+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}).replace(".",""), value: kind === "Receita" ? value : -value }); }
  return <div className="fixed inset-0 z-[70] bg-slate-950/40"><aside className="ml-auto h-full w-full max-w-md overflow-y-auto bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Nova transação</h2><button className="rounded-lg p-2 hover:bg-slate-100" onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-5 grid grid-cols-3 rounded-lg bg-slate-100 p-1">{["Receita","Despesa","Transferência"].map((item) => <button type="button" key={item} onClick={() => setKind(item)} className={cn("rounded-md px-2 py-2 text-sm",kind === item ? "bg-white font-semibold text-primary shadow-sm" : "text-slate-600")}>{item}</button>)}</div><form className="mt-5 space-y-4" onSubmit={submit}><Field label="Descrição"><input name="description" className={inputClass} required /></Field><Field label="Valor"><CurrencyInput onValueChange={setValue} required /></Field><Field label="Data"><input name="date" type="date" className={inputClass} required /></Field><Field label="Conta"><select name="account" className={inputClass}><option>Nubank</option><option>Poupança</option><option>Cartão</option></select></Field>{kind !== "Transferência" ? <Field label="Categoria"><select name="category" className={inputClass}><option>Alimentação</option><option>Moradia</option><option>Transporte</option><option>Salário</option></select></Field> : <Field label="Conta de destino"><select name="destination" className={inputClass}><option>Poupança</option><option>Nubank</option></select></Field>}<label className="flex items-center justify-between rounded-lg border p-3 text-sm">Recorrente<input type="checkbox" checked={recurring} onChange={(event) => setRecurring(event.target.checked)} /></label>{recurring && <Field label="Frequência"><select className={inputClass}><option>Mensal</option><option>Semanal</option><option>Anual</option></select></Field>}{kind === "Despesa" && <label className="flex items-center justify-between rounded-lg border p-3 text-sm">Parcelado<input type="checkbox" checked={installment} onChange={(event) => setInstallment(event.target.checked)} /></label>}{installment && <Field label="Quantidade de parcelas"><input type="number" min="2" max="48" defaultValue="2" className={inputClass} /></Field>}<div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit">Salvar transação</Button></div></form></aside></div>;
}

function ImportDialog({ open,onClose,onComplete }: { open:boolean;onClose:()=>void;onComplete:()=>void }) { const [step,setStep] = useState(1); return <Modal open={open} title="Importar extrato" onClose={onClose} footer={step === 1 ? <Button onClick={() => setStep(2)}>Continuar</Button> : <><Button variant="outline" onClick={() => setStep(1)}>Voltar</Button><Button onClick={onComplete}>Confirmar importação</Button></>}><div className="rounded-lg border border-dashed p-8 text-center"><Upload className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 font-medium">{step === 1 ? "Arraste seu extrato aqui" : "18 transações encontradas"}</p><p className="text-sm text-slate-500">{step === 1 ? "OFX, CSV ou PDF até 10MB" : "Categorias sugeridas pela IA estão prontas para revisão."}</p></div></Modal>; }
function Summary({ label,value }: { label:string;value:number }) { return <Card><p className="text-sm text-slate-500">{label}</p><Money className="mt-2 block text-2xl font-semibold" value={value} /></Card>; }
function IconButton({ label,icon:Icon,onClick,danger=false }: { label:string;icon:typeof Edit;onClick:()=>void;danger?:boolean }) { return <button onClick={onClick} className={cn("rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700",danger && "hover:bg-red-50 hover:text-red-600")} aria-label={label} title={label}><Icon className="h-4 w-4" /></button>; }
