import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Copy, Edit, Plus, Search, Trash2, Upload, X } from "lucide-react";
import { Badge, Button, Card, CurrencyInput, Field, Money, PageHeader, Skeleton, inputClass } from "../components/ui";
import { ConfirmDialog, Modal, useFeedback } from "../components/feedback";
import { cn } from "../lib/format";
import { api, toDateLabel, type Account, type Category, type Transaction } from "../lib/api";

type SummaryData = { income: number; expense: number; result: number };

export default function TransactionsPage() {
  const [items, setItems] = useState<Transaction[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [summary, setSummary] = useState<SummaryData>({ income: 0, expense: 0, result: 0 });
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(""); const [type, setType] = useState("Todas"); const [account, setAccount] = useState("Todas"); const [category, setCategory] = useState("Todas");
  const [minValue, setMinValue] = useState(""); const [maxValue, setMaxValue] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  const [drawerOpen, setDrawerOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [editing, setEditing] = useState<Transaction | null>(null); const [deleting, setDeleting] = useState<string[] | null>(null);
  const { notify } = useFeedback();

  async function load() {
    setLoading(true);
    try {
      const [transactions, accountData, categoryData] = await Promise.all([
        api<{ items: Transaction[]; summary: SummaryData }>("/transactions"),
        api<{ items: Account[] }>("/accounts"), api<{ items: Category[] }>("/categories"),
      ]);
      setItems(transactions.items); setSummary(transactions.summary); setAccounts(accountData.items); setCategories(categoryData.items);
    } catch (error) { notify(error instanceof Error ? error.message : "Falha ao carregar transações.", "error"); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);

  const filtered = useMemo(() => items.filter((item) => { const value = item.amount; return item.description.toLowerCase().includes(query.toLowerCase()) && (type === "Todas" || (type === "Receitas" && item.type === "income") || (type === "Despesas" && item.type === "expense")) && (account === "Todas" || item.account_id === account) && (category === "Todas" || item.category_id === category) && (!minValue || value >= Number(minValue)) && (!maxValue || value <= Number(maxValue)); }), [items, query, type, account, category, minValue, maxValue]);

  async function remove(ids: string[]) { try { await Promise.all(ids.map((id) => api(`/transactions/${id}`, { method: "DELETE" }))); setDeleting(null); setSelected([]); await load(); notify("Transação excluída."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao excluir.", "error"); } }
  async function duplicate(id: string) { try { await api(`/transactions/${id}/duplicate`, { method: "POST" }); await load(); notify("Transação duplicada."); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao duplicar.", "error"); } }

  return <>
    <PageHeader title="Transações" subtitle={`${items.length} lançamentos · resultado ${summary.result.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}`} actions={<><Button variant="outline" icon={Upload} onClick={() => setImportOpen(true)} disabled={!accounts.some((item) => item.status === "active")}>Importar CSV</Button><Button icon={Plus} onClick={() => { setEditing(null); setDrawerOpen(true); }} disabled={!accounts.some((item) => item.status === "active")}>Nova transação</Button></>} />
    {!accounts.length && <div className="mb-4 rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">Cadastre sua primeira conta no Dashboard antes de lançar movimentações.</div>}
    <Card className="sticky top-16 z-10 mb-4 shadow-sm lg:top-0"><div className="grid gap-3 lg:grid-cols-[minmax(220px,1.4fr)_280px_180px_180px]"><div className="relative"><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400" /><input className={cn(inputClass,"pl-10")} placeholder="Buscar transações..." value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="grid grid-cols-3 rounded-lg bg-slate-100 p-1">{["Todas","Receitas","Despesas"].map((item) => <button key={item} onClick={() => setType(item)} className={cn("rounded-md px-2 py-1.5 text-sm",type === item ? "bg-white font-semibold text-primary shadow-sm" : "text-slate-600")}>{item}</button>)}</div><select className={inputClass} value={account} onChange={(event) => setAccount(event.target.value)}><option value="Todas">Todas as contas</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={category} onChange={(event) => setCategory(event.target.value)}><option value="Todas">Todas categorias</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:max-w-md"><input className={inputClass} type="number" min="0" placeholder="Valor mínimo" value={minValue} onChange={(event) => setMinValue(event.target.value)} /><input className={inputClass} type="number" min="0" placeholder="Valor máximo" value={maxValue} onChange={(event) => setMaxValue(event.target.value)} /></div></Card>
    <section className="mb-4 grid gap-4 md:grid-cols-3"><Summary label="Total de receitas" value={summary.income} /><Summary label="Total de despesas" value={-summary.expense} /><Summary label="Resultado" value={summary.result} /></section>
    {selected.length > 0 && <div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border bg-blue-50 p-3 text-sm"><strong>{selected.length} selecionadas</strong><Button variant="danger" onClick={() => setDeleting(selected)}>Excluir</Button><Button variant="ghost" onClick={() => setSelected([])}>Cancelar</Button></div>}
    {loading ? <Skeleton className="h-72" /> : <Card className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="w-10 px-4 py-3"></th><th className="px-4 py-3">Descrição</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Conta</th><th className="px-4 py-3">Data</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3 text-right">Ações</th></tr></thead><tbody>{filtered.length === 0 && <tr><td colSpan={7} className="px-4 py-16 text-center"><strong className="block text-slate-800">Nenhuma transação encontrada</strong><span className="mt-1 block text-sm text-slate-500">Cadastre um lançamento ou ajuste os filtros.</span></td></tr>}{filtered.map((item) => <tr key={item.id} className="border-t hover:bg-slate-50"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current,item.id] : current.filter((value) => value !== item.id))} /></td><td className="px-4 py-3 font-medium">{item.description}</td><td className="px-4 py-3"><Badge>{item.category}</Badge></td><td className="px-4 py-3 text-slate-600">{item.account}</td><td className="px-4 py-3 text-slate-600">{toDateLabel(item.date)}</td><td className="px-4 py-3 text-right"><Money value={item.value} signed /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><IconButton label="Editar" icon={Edit} onClick={() => { setEditing(item); setDrawerOpen(true); }} /><IconButton label="Duplicar" icon={Copy} onClick={() => void duplicate(item.id)} /><IconButton label="Excluir" icon={Trash2} danger onClick={() => setDeleting([item.id])} /></div></td></tr>)}</tbody></table></div><div className="border-t px-4 py-3 text-sm text-slate-500">Mostrando {filtered.length} de {items.length} transações</div></Card>}
    {drawerOpen && <TransactionDrawer item={editing} accounts={accounts} categories={categories} onClose={() => setDrawerOpen(false)} onSaved={async () => { setDrawerOpen(false); await load(); notify("Transação salva com sucesso."); }} />}
    <ImportDialog open={importOpen} accounts={accounts} onClose={() => setImportOpen(false)} onComplete={async () => { setImportOpen(false); await load(); }} />
    <ConfirmDialog open={Boolean(deleting)} title="Excluir transação?" description={`${deleting?.length ?? 0} transação(ões) será(ão) excluída(s).`} onClose={() => setDeleting(null)} onConfirm={() => { if (deleting) void remove(deleting); }} />
  </>;
}

function TransactionDrawer({ item, accounts, categories, onClose, onSaved }: { item: Transaction | null; accounts: Account[]; categories: Category[]; onClose: () => void; onSaved: () => void }) {
  const [kind,setKind] = useState<"income"|"expense">(item?.type === "income" ? "income" : "expense"); const [value,setValue] = useState(item?.amount ?? 0); const [saving,setSaving] = useState(false); const { notify } = useFeedback();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (value <= 0) return notify("Informe um valor maior que zero.","error"); setSaving(true); try { await api(item ? `/transactions/${item.id}` : "/transactions", { method: item ? "PUT" : "POST", body: JSON.stringify({ description: data.get("description"), amount: value, date: data.get("date"), account_id: data.get("account_id"), category_id: data.get("category_id") || null, type: kind, is_recurring: data.get("recurring") === "on" }) }); onSaved(); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao salvar.", "error"); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-[70] bg-slate-950/40"><aside className="ml-auto h-full w-full max-w-md overflow-y-auto bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{item ? "Editar transação" : "Nova transação"}</h2><button className="rounded-lg p-2 hover:bg-slate-100" onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-5 grid grid-cols-2 rounded-lg bg-slate-100 p-1">{[["income","Receita"],["expense","Despesa"]].map(([value,label]) => <button type="button" key={value} onClick={() => setKind(value as "income"|"expense")} className={cn("rounded-md px-2 py-2 text-sm",kind === value ? "bg-white font-semibold text-primary shadow-sm" : "text-slate-600")}>{label}</button>)}</div><form className="mt-5 space-y-4" onSubmit={submit}><Field label="Descrição"><input name="description" className={inputClass} defaultValue={item?.description} required /></Field><Field label="Valor"><CurrencyInput initialValue={item?.amount} onValueChange={setValue} required /></Field><Field label="Data"><input name="date" type="date" className={inputClass} defaultValue={item?.date.slice(0,10) ?? new Date().toISOString().slice(0,10)} required /></Field><Field label="Conta"><select name="account_id" className={inputClass} defaultValue={item?.account_id}>{accounts.filter((account) => account.status === "active").map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="Categoria"><select name="category_id" className={inputClass} defaultValue={item?.category_id ?? ""}><option value="">Sem categoria</option>{categories.filter((category) => category.type === kind || category.type === "both").map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><label className="flex items-center justify-between rounded-lg border p-3 text-sm">Recorrente<input name="recurring" type="checkbox" /></label><div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? "Salvando..." : "Salvar transação"}</Button></div></form></aside></div>;
}
function Summary({ label,value }: { label:string;value:number }) { return <Card><p className="text-sm text-slate-500">{label}</p><Money className="mt-2 block text-2xl font-semibold" value={value} /></Card>; }
function IconButton({ label,icon:Icon,onClick,danger=false }: { label:string;icon:typeof Edit;onClick:()=>void;danger?:boolean }) { return <button onClick={onClick} className={cn("rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700",danger && "hover:bg-red-50 hover:text-red-600")} aria-label={label} title={label}><Icon className="h-4 w-4" /></button>; }

type ImportPreview = { id:string;file_name:string;total_records:number;items:Array<{date:string;description:string;type:string;amount:number}> };
function ImportDialog({open,accounts,onClose,onComplete}:{open:boolean;accounts:Account[];onClose:()=>void;onComplete:()=>void}) {
  const [file,setFile]=useState<File|null>(null);const [accountID,setAccountID]=useState(accounts.find(item=>item.status==="active")?.id??"");const [preview,setPreview]=useState<ImportPreview|null>(null);const [loading,setLoading]=useState(false);const {notify}=useFeedback();
  useEffect(()=>{if(!accountID)setAccountID(accounts.find(item=>item.status==="active")?.id??"");},[accounts,accountID]);
  async function upload(){if(!file||!accountID)return;setLoading(true);try{const form=new FormData();form.append("file",file);form.append("account_id",accountID);setPreview(await api<ImportPreview>("/imports",{method:"POST",body:form}));}catch(error){notify(error instanceof Error?error.message:"Falha ao processar CSV.","error");}finally{setLoading(false)}}
  async function confirm(){if(!preview)return;setLoading(true);try{const result=await api<{imported_records:number;duplicated_records:number}>(`/imports/${preview.id}/confirm`,{method:"POST"});notify(`${result.imported_records} transações importadas; ${result.duplicated_records} duplicadas ignoradas.`);setPreview(null);setFile(null);await onComplete();}catch(error){notify(error instanceof Error?error.message:"Falha ao confirmar importação.","error");}finally{setLoading(false)}}
  return <Modal open={open} title="Importar extrato CSV" subtitle="Use as colunas Data, Descrição e Valor. Despesas devem ter valor negativo." onClose={onClose} size="lg" footer={preview?<><Button variant="outline" onClick={()=>setPreview(null)}>Voltar</Button><Button onClick={()=>void confirm()} disabled={loading}>{loading?"Importando...":"Confirmar importação"}</Button></>:<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={()=>void upload()} disabled={!file||!accountID||loading}>{loading?"Processando...":"Pré-visualizar"}</Button></>}>
    {!preview?<div className="grid gap-4"><Field label="Conta de destino"><select className={inputClass} value={accountID} onChange={event=>setAccountID(event.target.value)}>{accounts.filter(item=>item.status==="active").map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><label className="rounded-lg border border-dashed p-8 text-center"><Upload className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-3 font-medium">Selecione o extrato CSV</p><input className="mt-4 block w-full text-sm" type="file" accept=".csv,text/csv" onChange={event=>setFile(event.target.files?.[0]??null)}/></label></div>:<div><p className="mb-3 text-sm text-slate-600"><strong>{preview.total_records}</strong> lançamentos encontrados em {preview.file_name}.</p><div className="max-h-72 overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50"><tr><th className="p-2 text-left">Data</th><th className="p-2 text-left">Descrição</th><th className="p-2 text-right">Valor</th></tr></thead><tbody>{preview.items.map((item,index)=><tr key={`${item.date}-${item.description}-${index}`} className="border-t"><td className="p-2">{toDateLabel(item.date)}</td><td className="p-2">{item.description}</td><td className="p-2 text-right"><Money value={item.type==="expense"?-item.amount:item.amount}/></td></tr>)}</tbody></table></div></div>}
  </Modal>;
}
